### ISSUE TITLE
在VMOS虚拟机 系统版本7.1报错

### ISSUE THREAD

**Issue by hduwhyso** [TonyJiangWJ/AutoScriptBase#25]
安卓12使用下面命令正常，我只是把main这里改成

let creditEntry = widgetUtils.widgetGetOne('我的')
log(creditEntry)

![image](https://github.com/TonyJiangWJ/AutoScriptBase/assets/67532273/ddd47e7c-b919-4810-8141-b1c851d9caae)

**### 以下是日志：**

07:15:27.620/V: 当前无任务等待，直接执行：{"source":"/data/user/0/com.taobao.idlefish.modify/cache/remote_project/fc79013cff5d4649e75c3852f1716dd4/2.js","engineId":67,"storageKey":"autoscript_version"}
07:15:27.621/V: 设置脚本状态为执行中
07:15:27.624/V: 当前脚本信息 id:67 source:/data/user/0/com.taobao.idlefish.modify/cache/remote_project/fc79013cff5d4649e75c3852f1716dd4/2.js 运行中脚本数量：1
07:15:27.625/D: ======校验无障碍功能======
07:15:27.655/E: android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo

java.lang.NoClassDefFoundError: android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo
	at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.Method.getReturnType(Method.java:150)
	at org.mozilla.javascript.JavaMembers.extractGetMethod(JavaMembers.java:697)
	at org.mozilla.javascript.JavaMembers.findGetter(JavaMembers.java:684)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:576)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:54)
	at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:827)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:786)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:50)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:44)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:40)
	at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:136)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:134)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2023)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1559)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.AccessorSlot$FunctionGetter.getValue(AccessorSlot.java:128)
	at org.mozilla.javascript.AccessorSlot.getValue(AccessorSlot.java:65)
	at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:241)
	at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:367)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2023)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1559)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.Context.callFunctionWithContinuations(Context.java:1225)
	at org.mozilla.javascript.Context.executeScriptWithContinuations(Context.java:1193)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:97)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:22)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:20)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:45)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:64)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:37)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:57)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:51)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:37)
	at java.lang.Thread.run(Thread.java:761)
	at com.stardust.lang.ThreadCompat.run(ThreadCompat.java:78)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo" on path: DexPathList[[zip file "/data/app/com.taobao.idlefish.modify-1/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.idlefish.modify-1/lib/arm, /data/app/com.taobao.idlefish.modify-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.Method.getReturnType(Method.java:150)
	at org.mozilla.javascript.JavaMembers.extractGetMethod(JavaMembers.java:697)
	at org.mozilla.javascript.JavaMembers.findGetter(JavaMembers.java:684)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:576)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:54)
	at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:827)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:786)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:50)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:44)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:40)
	at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:136)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:134)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2023)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1559)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.AccessorSlot$FunctionGetter.getValue(AccessorSlot.java:128)
	at org.mozilla.javascript.AccessorSlot.getValue(AccessorSlot.java:65)
	at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:241)
	at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:367)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2023)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1672)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1667)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1559)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.Context.callFunctionWithContinuations(Context.java:1225)
	at org.mozilla.javascript.Context.executeScriptWithContinuations(Context.java:1193)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:97)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:22)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:20)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:45)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:64)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:37)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:57)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:51)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:37)
	at java.lang.Thread.run(Thread.java:761)
	at com.stardust.lang.ThreadCompat.run(ThreadCompat.java:78)
07:15:27.657/V: 
------------
[/data/user/0/com.taobao.idlefish.modify/cache/remote_project/fc79013cff5d4649e75c3852f1716dd4/2.js]运行结束，用时0.384000秒
07:15:27.658/V: 脚本已经中止执行，执行生命周期回调

**Comment by TonyJiangWJ** [comment]
魔改版完整功能只支持安卓8以上，低于安卓8的自行换旧版本aj
